{
    DiffBn_coarse: 4,
    DiffBn_fine: 39,
    OFFBn_coarse: 4,
    OFFBn_fine: 0,
    ONBn_coarse: 5,
    ONBn_fine: 200,
    PrBp_coarse: 2,
    PrBp_fine: 58,
    PrSFBp_coarse: 1,
    PrSFBp_fine: 33,
    RefrBp_coarse: 4,
    RefrBp_fine: 25,
    aps_enabled: true,
    dvs_enabled: true,
    exposure: 100000,
    autoexposure_enabled: true,
    autoexposure_desired_intensity: 75,
    autoexposure_gain: 3,
    frame_delay: 0,
    imu_acc_scale: 3,
    imu_enabled: true,
    imu_gyro_scale: 3,
    max_events: 0,
    streaming_rate: 30
}
